### ISSUE TITLE
many views toast all together bug!!!

### ISSUE THREAD

**Issue by wwwang89** [scalessec/Toast#105]
when I Click a button many times，and so  the method :   makeToast： will call many times，so that ，many toast views  will show，it looks strange，like the file below
![Uploading 511F9830-55D9-43AC-B9D0-D102B57AB13D.png…]()

so there exists a bug ？and why not use a Singleton ？ or check if a toast view show or not when we call the method makeToast ？ thanks

**Comment by wwwang89** [comment]
![511f9830-55d9-43ac-b9d0-d102b57ab13d](https://user-images.githubusercontent.com/3423535/26970677-cdd0b020-4d3c-11e7-86f2-998cddcc96d4.png)

**Comment by wwwang89** [comment]
![a744384e-e86f-4c6d-9f1b-20d929981c95](https://user-images.githubusercontent.com/3423535/26970807-380456e0-4d3d-11e7-8f85-9e6486bb07db.png)

the normal toast view is here and the above is not normal

**Comment by scalessec** [comment]
What you're seeing is the shadows layered on top of one another. You can change or modify the shadow in `CSToastStyle`. A singleton is not a good solution, because any UIView instance can display a toast and they can all display simultaneously if desired. Feel free to fork to get the behavior you want.
