### ISSUE TITLE
Feature request: [Toast makeToast:@"something"];

### ISSUE THREAD

**Issue by hoangtx90** [scalessec/Toast#72]
For now, the only way to toast is to call it from a specific view.
```Objective-C
[someView makeToast:@"oops"];
```
But what if we don't care about the view, what if we just want to display a toast right away regardless of where we are. Like:
```Objective-C
[Toast makeToast:@"oops"];
```
What do you think about this? Are we going to implement it in the future?

**Comment by scalessec** [comment]
Toast must be presented in a view. Making the library take a wild guess as to which view you want to present it in is never going to work reliably, and defaulting to the window is never a good idea because it disrupts the concept of a view hierarchy (plus, I don't believe the window is available in app extensions anyway).
